### ISSUE TITLE
5 minute warning sometimes going too early

### ISSUE THREAD

**Issue by OneStone2** [c0nD/FluffyBOT#20]
![imatge](https://user-images.githubusercontent.com/20133956/216380395-952bd22f-df07-4a61-a375-d2bd10ac0e7b.png)
note: in this screenshot the warning got sent shortly after ryrong posted an image, maybe try reproducing that

**Comment by c0nD** [comment]
https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.cancel

**Comment by c0nD** [comment]
![image](https://user-images.githubusercontent.com/90937263/216417034-79baddc3-0c11-40ba-af27-671df221af2e.png)
