### ISSUE TITLE
queue advancement without done prompt

### ISSUE THREAD

**Issue by c0nD** [c0nD/FluffyBOT#51]
sometimes, the queue will push people forward even if nobody has attacking and called "done"

ive noticed this happen mostly when people join the queue in expectation of a sweeper.

**Comment by ReinSonozaki** [comment]
![image](https://user-images.githubusercontent.com/125747705/221074857-16f4744f-debb-4adc-b91b-47c012c8567d.png)

Looks like its when there is a reaction to fluffy, it pushes the queue

**Comment by c0nD** [comment]
![image](https://user-images.githubusercontent.com/90937263/221376521-20e37426-1d65-42ef-89cb-f6621c8ed22b.png)


It sometimes will happen when you add any reaction to any message. Blue arrows = it triggered when reacted to this message.

**Comment by c0nD** [comment]
Issues has been fixed.

Closed.
